[workspace]
authors = ["unfaa3 <xujiacheng1016@hotmail.com>"]
channels = ["conda-forge"]
name = "calibration"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
opencv = ">=4.11.0,<5"
scipy = ">=1.15.2,<2"
pyrealsense2 = ">=2.54.2,<3"
pandas = ">=2.2.3,<3"
pynput = ">=1.8.1,<2"
